language: objective-c
osx_image: xcode7.3
xcode_project: mala-ios.xcodeproj # path to your xcodeproj folder
xcode_scheme: parent
xcode_sdk: iphonesimulator8.4
# command to install dependencies

# command to run tests
