language: objective-c
cache: cocoapods
rvm: 2.3

osx_image: xcode7.3
xcode_workspace: mala-ios.xcworkspace
xcode_scheme: parent-dev #[parent-dev, parent-stage, parent-prd]
xcode_sdk: iphonesimulator9.3


before_install:
- pod --version
- brew --version
- xctool -version
- xcodebuild -version -sdk
- rvm list known
- gem install fir-cli
install:
- pod repo remove master
- pod setup
- pod install
before_script:
- openssl aes-256-cbc -k $ENCRYPTION_SECRET -in scripts/profile/mala_dev_AdHoc.mobileprovision.enc -d -a -out scripts/profile/Mala_DevAdHoc.mobileprovision
- openssl aes-256-cbc -k $ENCRYPTION_SECRET -in scripts/profile/mala_prd_AdHoc.mobileprovision.enc -d -a -out scripts/profile/Mala_PrdAdHoc.mobileprovision
- openssl aes-256-cbc -k $ENCRYPTION_SECRET -in scripts/profile/mala_stage_AdHoc.mobileprovision.enc -d -a -out scripts/profile/Mala_StageAdHoc.mobileprovision
- openssl aes-256-cbc -k $ENCRYPTION_SECRET -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k $ENCRYPTION_SECRET -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
# script:
# - xctool -workspace mala-ios.xcworkspace -scheme parent-dev -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="parent-dev"
  - $DEVELOPER_NAME
  - PROFILE_NAME="Mala_DevAdHoc"
