language: objective-c
osx_image: xcode7.3
xcode_project: mala-ios.xcodeproj # path to your xcodeproj folder
xcode_scheme: [parent-dev, parent-stage, parent-prd]
xcode_sdk: iphonesimulator9.3
before_install:
     - brew update
     - brew install xctool
# command to install dependencies
#     - pod repo remove master
#     - pod repo add master https://git.coding.net/akuandev/Specs.git
#     - pod setup
    - pod repo update

# command to run tests
