language: objective-c

script:
  - xcodebuild -workspace mala-ios.xcworkspace -scheme parent-dev -sdk iphonesimulator ONLY_ACTIVE_ARCH=NOa
  - xcodebuild -workspace mala-ios.xcworkspace -scheme parent-dev -sdk iphonesimulator ONLY_ACTIVE_ARCH=NOa
  - xcodebuild -workspace mala-ios.xcworkspace -scheme parent-dev -sdk iphonesimulator ONLY_ACTIVE_ARCH=NOa

cache: cocoapods

# osx_image: xcode7.3
# xcode_project: mala-ios.xcodeproj # path to your xcodeproj folder
# xcode_scheme: [parent-dev, parent-stage, parent-prd]
# xcode_sdk: iphonesimulator9.3

before_install:
  - pod --version
  - brew --version
  - xctool -version
  - xcodebuild -version -sdk
  - rvm list known

  - rvm reinstall ruby-2.3.0
  - sudo gem install cocoapods
  - pod repo remove master  
  - pod setup

# command to install dependencies
#     - pod repo remove master
#     - pod repo add master https://git.coding.net/akuandev/Specs.git
#     - pod setup
#    - pod repo update

# command to run tests
