language: objective-c
cache: cocoapods
rvm: 2.3

osx_image: xcode7.3
xcode_workspace: mala-ios.xcworkspace
xcode_scheme: parent-dev #[parent-dev, parent-stage, parent-prd]
xcode_sdk: iphonesimulator9.3

# command to show version for debug
before_install:
  - pod --version
  - brew --version
  - xctool -version
  - xcodebuild -version -sdk
  - rvm list known

# command to install dependencies
install:
  # - rvm reinstall ruby-2.3.0
  # - sudo gem install cocoapods
  - pod repo remove master  # for clean cocoapods tool cache
  - pod setup
  - pod install

# command to build
# script:
#   - xcodebuild -workspace mala-ios.xcworkspace -scheme parent-dev -sdk iphonesimulator ONLY_ACTIVE_ARCH=NOa

# command to run tests
